### ISSUE TITLE
Investigate whether LaunchInfo object in nvshmem launch is too big

### ISSUE THREAD

**Issue by BenBrock** [berkeley-container-library/bcl#5]
Investigate whether LaunchInfo object in nvshmem launch is too big, leading it to take up too many registers.

**Comment by BenBrock** [comment]
The relevant code is [here](https://github.com/berkeley-container-library/bcl/blob/nvshmem/bcl/containers/experimental/cuda/launch_kernel.cuh#L12)

**Comment by YuxinxinChen** [comment]
If passing an object by value and in the object, there are more object members than the members used by the kernel, this doesn’t change the register usage of the kernel.
