### ISSUE TITLE
Backoff does not back off

### ISSUE THREAD

**Issue by JiakunYan** [berkeley-container-library/bcl#6]
The method `Backoff::backoff()` does not increase sleeping time.
I think it should invoke `increase_backoff_impl_()` in its function body.
```
void backoff() {
  usleep(sleep_time_);
}

void increase_backoff_impl_() {
  sleep_time_ = backoff_fn_(sleep_time_);
  sleep_time_ = std::max(sleep_time_, max_sleep_);
}
```

**Comment by BenBrock** [comment]
Feel free to open a pull request to fix this.
